//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyMngtSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Students = new HashSet<Student>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public int TeachersId { get; set; }
        public int StudentsId { get; set; }
        public string Name { get; set; }
        public int ClassRoom { get; set; }
        public string Teacher { get; set; }
        public int Mentor { get; set; }
        public Nullable<int> Capacity { get; set; }
        public int EducationProgram { get; set; }
        public bool Status { get; set; }
    
        public virtual ClassRoom ClassRoom1 { get; set; }
        public virtual Education Education { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
