//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyMngtSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskGroup
    {
        public int TaskId { get; set; }
        public int StudentId { get; set; }
        public Nullable<double> point { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
